_wandb:
    value:
        cli_version: 0.20.0
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 55
            "4": 3.11.11
            "5": 0.20.0
            "12": 0.20.0
            "13": darwin-arm64
